In [ ]:
!git clone https://github.com/PhonePe/pulse.git

Cloning into 'pulse'...
Updating files:  15% (1435/9029)
Updating files:  16% (1445/9029)
Updating files:  17% (1535/9029)
Updating files:  18% (1626/9029)
Updating files:  19% (1716/9029)
Updating files:  20% (1806/9029)
Updating files:  21% (1897/9029)
Updating files:  22% (1987/9029)
Updating files:  23% (2077/9029)
Updating files:  24% (2167/9029)
Updating files:  25% (2258/9029)
Updating files:  26% (2348/9029)
Updating files:  27% (2438/9029)
Updating files:  28% (2529/9029)
Updating files:  29% (2619/9029)
Updating files:  30% (2709/9029)
Updating files:  31% (2799/9029)
Updating files:  32% (2890/9029)
Updating files:  33% (2980/9029)
Updating files:  33% (3025/9029)
Updating files:  34% (3070/9029)
Updating files:  35% (3161/9029)
Updating files:  36% (3251/9029)
Updating files:  37% (3341/9029)
Updating files:  38% (3432/9029)
Updating files:  39% (3522/9029)
Updating files:  40% (3612/9029)
Updating files:  41% (3702/9029)
Updating files:  42% (3793/9029)
Updating files:  43% (3883/9029)
Updating files:  44% (3973/9029)
Updating files:  45% (4064/9029)
Updating files:  46% (4154/9029)
Updating files:  47% (4244/9029)
Updating files:  48% (4334/9029)
Updating files:  49% (4425/9029)
Updating files:  50% (4515/9029)
Updating files:  51% (4605/9029)
Updating files:  51% (4607/9029)
Updating files:  52% (4696/9029)
Updating files:  53% (4786/9029)
Updating files:  54% (4876/9029)
Updating files:  55% (4966/9029)
Updating files:  56% (5057/9029)
Updating files:  57% (5147/9029)
Updating files:  58% (5237/9029)
Updating files:  59% (5328/9029)
Updating files:  60% (5418/9029)
Updating files:  61% (5508/9029)
Updating files:  62% (5598/9029)
Updating files:  63% (5689/9029)
Updating files:  64% (5779/9029)
Updating files:  65% (5869/9029)
Updating files:  66% (5960/9029)
Updating files:  67% (6050/9029)
Updating files:  68% (6140/9029)
Updating files:  69% (6231/9029)
Updating files:  70% (6321/9029)
Updating files:  71% (6411/9029)
Updating files:  72% (6501/9029)
Updating files:  73% (6592/9029)
Updating files:  73% (6644/9029)
Updating files:  74% (6682/9029)
Updating files:  75% (6772/9029)
Updating files:  76% (6863/9029)
Updating files:  77% (6953/9029)
Updating files:  78% (7043/9029)
Updating files:  79% (7133/9029)
Updating files:  80% (7224/9029)
Updating files:  81% (7314/9029)
Updating files:  82% (7404/9029)
Updating files:  83% (7495/9029)
Updating files:  84% (7585/9029)
Updating files:  85% (7675/9029)
Updating files:  85% (7689/9029)
Updating files:  86% (7765/9029)
Updating files:  87% (7856/9029)
Updating files:  88% (7946/9029)
Updating files:  89% (8036/9029)
Updating files:  90% (8127/9029)
Updating files:  91% (8217/9029)
Updating files:  91% (8273/9029)
Updating files:  92% (8307/9029)
Updating files:  93% (8397/9029)
Updating files:  94% (8488/9029)
Updating files:  95% (8578/9029)
Updating files:  96% (8668/9029)
Updating files:  97% (8759/9029)
Updating files:  98% (8849/9029)
Updating files:  99% (8939/9029)
Updating files: 100% (9029/9029)
Updating files: 100% (9029/9029), done.

In [ ]:
import os
import json
import pandas as pd

In [2]:
#Aggregated_insurance

path1= r"C:\Users\Devendra\python\pulse\data\aggregated\insurance\country\india\state"

agg_insur_list= os.listdir(path1)

columns1= {"States":[], "Years":[], "Quarter":[], "Insurance_type":[], "Insurance_count":[],"Insurance_amount":[] }

for state in agg_insur_list:
    cur_states =os.path.join(path1, state)
    agg_year_list = os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_years = os.path.join(cur_states, year)
        agg_file_list = os.listdir(cur_years)

        for file in agg_file_list:
            cur_files = os.path.join(cur_years, file)
            data = open(cur_files,"r")
            A = json.load(data)

            for i in A["data"]["transactionData"]:
                name = i["name"]
                count = i["paymentInstruments"][0]["count"]
                amount = i["paymentInstruments"][0]["amount"]
                columns1["Insurance_type"].append(name)
                columns1["Insurance_count"].append(count)
                columns1["Insurance_amount"].append(amount)
                columns1["States"].append(state)
                columns1["Years"].append(year)
                columns1["Quarter"].append(int(file.strip(".json")))


aggre_insurance = pd.DataFrame(columns1)

aggre_insurance["States"] = aggre_insurance["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
aggre_insurance["States"] = aggre_insurance["States"].str.replace("-"," ")
aggre_insurance["States"] = aggre_insurance["States"].str.title()
aggre_insurance['States'] = aggre_insurance['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [3]:
aggre_insurance.head()

,States,Years,Quarter,Insurance_type,Insurance_count,Insurance_amount
0,Andaman & Nicobar,2020,2,Insurance,6,1360.0
1,Andaman & Nicobar,2020,3,Insurance,41,15380.0
2,Andaman & Nicobar,2020,4,Insurance,124,157975.0
3,Andaman & Nicobar,2021,1,Insurance,225,244266.0
4,Andaman & Nicobar,2021,2,Insurance,137,181504.0

In [4]:
#aggre_transaction
path2 = r"C:\Users\Devendra\python\pulse\data\aggregated\transaction\country\india\state"
         
agg_tran_list = os.listdir(path2)

columns2 ={"States":[], "Years":[], "Quarter":[], "Transaction_type":[], "Transaction_count":[],"Transaction_amount":[] }

for state in agg_tran_list:
    cur_states =os.path.join(path2, state)
    agg_year_list = os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_years = os.path.join(cur_states, year)
        agg_file_list = os.listdir(cur_years)

        for file in agg_file_list:
            cur_files = os.path.join(cur_years, file)
            data = open(cur_files,"r")
            B = json.load(data)

            for i in B["data"]["transactionData"]:
                name = i["name"]
                count = i["paymentInstruments"][0]["count"]
                amount = i["paymentInstruments"][0]["amount"]
                columns2["Transaction_type"].append(name)
                columns2["Transaction_count"].append(count)
                columns2["Transaction_amount"].append(amount)
                columns2["States"].append(state)
                columns2["Years"].append(year)
                columns2["Quarter"].append(int(file.strip(".json")))

aggre_transaction = pd.DataFrame(columns2)

aggre_transaction["States"] = aggre_transaction["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
aggre_transaction["States"] = aggre_transaction["States"].str.replace("-"," ")
aggre_transaction["States"] = aggre_transaction["States"].str.title()
aggre_transaction['States'] = aggre_transaction['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [5]:
aggre_transaction.head()

,States,Years,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2018,1,Recharge & bill payments,4200,1.845307e+06
1,Andaman & Nicobar,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,Andaman & Nicobar,2018,1,Merchant payments,298,4.525072e+05
3,Andaman & Nicobar,2018,1,Financial Services,33,1.060142e+04
4,Andaman & Nicobar,2018,1,Others,256,1.846899e+05

In [6]:
#aggre_user
path3 = r"C:\Users\Devendra\python\pulse\data\aggregated\user\country\india\state"
         
agg_user_list = os.listdir(path3)

columns3 = {"States":[], "Years":[], "Quarter":[], "Brands":[],"Transaction_count":[], "Percentage":[]}

for state in agg_user_list:
    cur_states = os.path.join(path3, state)
    agg_year_list = os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_years = os.path.join(cur_states, year)
        agg_file_list = os.listdir(cur_years)
        
        for file in agg_file_list:
            cur_files =os.path.join (cur_years, file)
            data = open(cur_files,"r")
            C = json.load(data)

            try:

                for i in C["data"]["usersByDevice"]:
                    brand = i["brand"]
                    count = i["count"]
                    percentage = i["percentage"]
                    columns3["Brands"].append(brand)
                    columns3["Transaction_count"].append(count)
                    columns3["Percentage"].append(percentage)
                    columns3["States"].append(state)
                    columns3["Years"].append(year)
                    columns3["Quarter"].append(int(file.strip(".json")))
            
            except:
                pass

aggre_user = pd.DataFrame(columns3)

aggre_user["States"] = aggre_user["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
aggre_user["States"] = aggre_user["States"].str.replace("-"," ")
aggre_user["States"] = aggre_user["States"].str.title()
aggre_user['States'] = aggre_user['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [7]:
aggre_user.head()

              States Years  Quarter   Brands  Transaction_count  Percentage
0  Andaman & Nicobar  2018        1   Xiaomi               1665    0.247033
1  Andaman & Nicobar  2018        1  Samsung               1445    0.214392
2  Andaman & Nicobar  2018        1     Vivo                982    0.145697
3  Andaman & Nicobar  2018        1     Oppo                501    0.074332
4  Andaman & Nicobar  2018        1  OnePlus                332    0.049258

# map

In [8]:
#map_insurance
path4 = r"C:\Users\Devendra\python\pulse\data\map\insurance\hover\country\india\state"
map_insur_list= os.listdir(path4)

columns4= {"States":[], "Years":[], "Quarter":[], "Districts":[], "Transaction_count":[],"Transaction_amount":[] }

for state in map_insur_list:
    cur_states =os.path.join(path4, state)
    agg_year_list = os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_years = os.path.join(cur_states, year)
        agg_file_list = os.listdir(cur_years)

        for file in agg_file_list:
            cur_files = os.path.join(cur_years, file)
            data = open(cur_files,"r")
            D = json.load(data)

            for i in D["data"]["hoverDataList"]:
                name = i["name"]
                count = i["metric"][0]["count"]
                amount = i["metric"][0]["amount"]
                columns4["Districts"].append(name)
                columns4["Transaction_count"].append(count)
                columns4["Transaction_amount"].append(amount)
                columns4["States"].append(state)
                columns4["Years"].append(year)
                columns4["Quarter"].append(int(file.strip(".json")))


map_insurance = pd.DataFrame(columns4)

map_insurance["States"] = map_insurance["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_insurance["States"] = map_insurance["States"].str.replace("-"," ")
map_insurance["States"] = map_insurance["States"].str.title()
map_insurance['States'] = map_insurance['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [9]:
map_insurance.head(3)

,States,Years,Quarter,Districts,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2020,2,south andaman district,3,795.0
1,Andaman & Nicobar,2020,2,nicobars district,3,565.0
2,Andaman & Nicobar,2020,3,north and middle andaman district,1,281.0

In [10]:
path5 = r"C:\Users\Devendra\python\pulse\data\map\transaction\hover\country\india\state"
map_tran_list = os.listdir(path5)

columns5 = {"States":[], "Years":[], "Quarter":[],"District":[], "Transaction_count":[],"Transaction_amount":[]}

for state in map_tran_list:
    cur_states = os.path.join(path5, state)
    map_year_list = os.listdir(cur_states)
    
    for year in map_year_list:
        cur_years = os.path.join(cur_states, year)
        map_file_list = os.listdir(cur_years)
        
        for file in map_file_list:
            cur_files = os.path.join(cur_years, file)
            data = open(cur_files,"r")
            E = json.load(data)

            for i in E['data']["hoverDataList"]:
                name = i["name"]
                count = i["metric"][0]["count"]
                amount = i["metric"][0]["amount"]
                columns5["District"].append(name)
                columns5["Transaction_count"].append(count)
                columns5["Transaction_amount"].append(amount)
                columns5["States"].append(state)
                columns5["Years"].append(year)
                columns5["Quarter"].append(int(file.strip(".json")))

map_transaction = pd.DataFrame(columns5)

map_transaction["States"] = map_transaction["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_transaction["States"] = map_transaction["States"].str.replace("-"," ")
map_transaction["States"] = map_transaction["States"].str.title()
map_transaction['States'] = map_transaction['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [11]:
map_transaction.head(3)

,States,Years,Quarter,District,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2018,1,north and middle andaman district,442,9.316631e+05
1,Andaman & Nicobar,2018,1,south andaman district,5688,1.256025e+07
2,Andaman & Nicobar,2018,1,nicobars district,528,1.139849e+06

In [12]:
path6 = r"C:\Users\Devendra\python\pulse\data\map\user\hover\country\india\state"
map_user_list = os.listdir(path6)

columns6 = {"States":[], "Years":[], "Quarter":[], "Districts":[], "RegisteredUser":[], "AppOpens":[]}

for state in map_user_list:
    cur_states = os.path.join(path6, state)
    map_year_list = os.listdir(cur_states)
    
    for year in map_year_list:
        cur_years = os.path.join(cur_states, year)
        map_file_list = os.listdir(cur_years)
        
        for file in map_file_list:
            cur_files = os.path.join(cur_years, file)
            data = open(cur_files,"r")
            F = json.load(data)

            for i in F["data"]["hoverData"].items():
                district = i[0]
                registereduser = i[1]["registeredUsers"]
                appopens = i[1]["appOpens"]
                columns6["Districts"].append(district)
                columns6["RegisteredUser"].append(registereduser)
                columns6["AppOpens"].append(appopens)
                columns6["States"].append(state)
                columns6["Years"].append(year)
                columns6["Quarter"].append(int(file.strip(".json")))

map_user = pd.DataFrame(columns6)

map_user["States"] = map_user["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_user["States"] = map_user["States"].str.replace("-"," ")
map_user["States"] = map_user["States"].str.title()
map_user['States'] = map_user['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [13]:
map_user.head(3)

,States,Years,Quarter,Districts,RegisteredUser,AppOpens
0,Andaman & Nicobar,2018,1,north and middle andaman district,632,0
1,Andaman & Nicobar,2018,1,south andaman district,5846,0
2,Andaman & Nicobar,2018,1,nicobars district,262,0

# top

In [14]:
path7 = r"C:\Users\Devendra\python\pulse\data\top\insurance\country\india\state"
top_insur_list = os.listdir(path7)

columns7 = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}

for state in top_insur_list:
    cur_states = os.path.join(path7, state)
    top_year_list = os.listdir(cur_states)

    for year in top_year_list:
        cur_years = os.path.join(cur_states, year)
        top_file_list = os.listdir(cur_years)

        for file in top_file_list:
            cur_files = os.path.join(cur_years, file)
            data = open(cur_files,"r")
            G = json.load(data)

            for i in G["data"]["pincodes"]:
                entityName = i["entityName"]
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                columns7["Pincodes"].append(entityName)
                columns7["Transaction_count"].append(count)
                columns7["Transaction_amount"].append(amount)
                columns7["States"].append(state)
                columns7["Years"].append(year)
                columns7["Quarter"].append(int(file.strip(".json")))

top_insur = pd.DataFrame(columns7)

top_insur["States"] = top_insur["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
top_insur["States"] = top_insur["States"].str.replace("-"," ")
top_insur["States"] = top_insur["States"].str.title()
top_insur['States'] = top_insur['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [15]:
print(top_insur.dtypes)
print(top_insur.isnull().sum())

States                    str
Years                     str
Quarter                 int64
Pincodes                  str
Transaction_count       int64
Transaction_amount    float64
dtype: object
States                0
Years                 0
Quarter               0
Pincodes              3
Transaction_count     0
Transaction_amount    0
dtype: int64

In [16]:
top_insur[top_insur["Pincodes"].isna()]

      States Years  Quarter Pincodes  Transaction_count  Transaction_amount
3199  Ladakh  2020        3      NaN                  1               281.0
3207  Ladakh  2020        4      NaN                  1               658.0
3284  Ladakh  2022        4      NaN                  8             16020.0

In [17]:
top_insur["Pincodes"] = top_insur["Pincodes"].fillna("Unknown")

In [18]:
top_insur.head(2)

,States,Years,Quarter,Pincodes,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2020,2,744301,3,565.0
1,Andaman & Nicobar,2020,2,744104,2,513.0

In [19]:
path8 = r"C:\Users\Devendra\python\pulse\data\top\transaction\country\india\state"
top_tran_list = os.listdir(path8)

columns8 = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}

for state in top_tran_list:
    cur_states = os.path.join(path8,state)
    top_year_list = os.listdir(cur_states)
    
    for year in top_year_list:
        cur_years = os.path.join(cur_states, year)
        top_file_list = os.listdir(cur_years)
        
        for file in top_file_list:
            cur_files = os.path.join(cur_years, file)
            data = open(cur_files,"r")
            H = json.load(data)

            for i in H["data"]["pincodes"]:
                entityName = i["entityName"]
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                columns8["Pincodes"].append(entityName)
                columns8["Transaction_count"].append(count)
                columns8["Transaction_amount"].append(amount)
                columns8["States"].append(state)
                columns8["Years"].append(year)
                columns8["Quarter"].append(int(file.strip(".json")))

top_transaction = pd.DataFrame(columns8)

top_transaction["States"] = top_transaction["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
top_transaction["States"] = top_transaction["States"].str.replace("-"," ")
top_transaction["States"] = top_transaction["States"].str.title()
top_transaction['States'] = top_transaction['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [20]:
print(top_transaction.dtypes)
print(top_transaction.isnull().sum())

States                    str
Years                     str
Quarter                 int64
Pincodes                  str
Transaction_count       int64
Transaction_amount    float64
dtype: object
States                0
Years                 0
Quarter               0
Pincodes              2
Transaction_count     0
Transaction_amount    0
dtype: int64

In [21]:
top_transaction["Pincodes"] = top_transaction["Pincodes"].fillna("Unknown")

In [22]:
top_transaction.head()

,States,Years,Quarter,Pincodes,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2018,1,744101,1622,2.769298e+06
1,Andaman & Nicobar,2018,1,744103,1223,2.238042e+06
2,Andaman & Nicobar,2018,1,744102,969,3.519060e+06
3,Andaman & Nicobar,2018,1,744105,685,1.298561e+06
4,Andaman & Nicobar,2018,1,744104,340,1.039715e+06

In [23]:
path9 = r"C:\Users\Devendra\python\pulse\data\top\user\country\india\state"
top_user_list=os.listdir(path9)
columns9 = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "RegisteredUser":[]}
for state in top_user_list:
    cur_states = os.path.join(path9,state)
    top_year_list = os.listdir(cur_states)

    for year in top_year_list:
        cur_years = os.path.join(cur_states, year)
        top_file_list = os.listdir(cur_years)

        for file in top_file_list:
            cur_files = os.path.join(cur_years, file)
            data = open(cur_files,"r")
            I = json.load(data)

            for i in I["data"]["pincodes"]:
                name = i["name"]
                registeredusers = i["registeredUsers"]
                columns9["Pincodes"].append(name)
                columns9["RegisteredUser"].append(registereduser)
                columns9["States"].append(state)
                columns9["Years"].append(year)
                columns9["Quarter"].append(int(file.strip(".json")))

top_user = pd.DataFrame(columns9)

top_user["States"] = top_user["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
top_user["States"] = top_user["States"].str.replace("-"," ")
top_user["States"] = top_user["States"].str.title()
top_user['States'] = top_user['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [24]:
print(top_user.dtypes)
print(top_user.isnull().sum())

States              str
Years               str
Quarter           int64
Pincodes            str
RegisteredUser    int64
dtype: object
States            0
Years             0
Quarter           0
Pincodes          0
RegisteredUser    0
dtype: int64

In [25]:
top_user.head(2)

              States Years  Quarter Pincodes  RegisteredUser
0  Andaman & Nicobar  2018        1   744103         1717074
1  Andaman & Nicobar  2018        1   744101         1717074

# SQL connection

In [26]:
import pyodbc

In [27]:
import pyodbc

conn = pyodbc.connect(
    "Driver={ODBC Driver 18 for SQL Server};"
    "Server=DESKTOP-55JNORK\\SQLEXPRESS;"
    "Database=phonepe;"
    "Trusted_Connection=yes;"
    "TrustServerCertificate=yes;"
)

cursor = conn.cursor()
print("Connected Successfully!")

Connected Successfully!

In [28]:
insert_query1 = """
INSERT INTO aggregated_insurance
(States, Years, Quarter, Insurance_type, Insurance_count, Insurance_amount)
VALUES (?, ?, ?, ?, ?, ?)
"""

data1 = aggre_insurance.values.tolist()

cursor.executemany(insert_query1, data1)
conn.commit()

print("Insurance data inserted successfully!")

Insurance data inserted successfully!

In [29]:
#aggregated transaction table
insert_query2 = """
INSERT INTO aggregated_transaction
(States, Years, Quarter, Transaction_type, Transaction_count, Transaction_amount)
VALUES (?, ?, ?, ?, ?, ?)
"""

data2 = aggre_transaction.values.tolist()

cursor.executemany(insert_query2, data2)
conn.commit()

print("Data inserted successfully!")

Data inserted successfully!

In [30]:
insert_query3 = """
INSERT INTO aggregated_user
(States, Years, Quarter, Brands, Transaction_count, Percentage)
VALUES (?, ?, ?, ?, ?, ?)
"""

data3 = aggre_user.values.tolist()

cursor.executemany(insert_query3, data3)
conn.commit()

print("Data inserted successfully!")

Data inserted successfully!

# map

In [31]:
insert_query4 = """
INSERT INTO map_insurance
(States, Years, Quarter, Districts, Transaction_count, Transaction_amount)
VALUES (?, ?, ?, ?, ?, ?)
"""

data4 = map_insurance.values.tolist()

cursor.executemany(insert_query4, data4)
conn.commit()

print("Map Insurance data inserted successfully!")

Map Insurance data inserted successfully!

In [32]:
insert_query5 = """
INSERT INTO map_transaction
(States, Years, Quarter, District, Transaction_count, Transaction_amount)
VALUES (?, ?, ?, ?, ?, ?)
"""

data5 = map_transaction.values.tolist()

cursor.executemany(insert_query5, data5)
conn.commit()

print("Map Transaction data inserted successfully!")

Map Transaction data inserted successfully!

In [33]:
insert_query6 = """
INSERT INTO map_user
(States, Years, Quarter, Districts, RegisteredUser, AppOpens)
VALUES (?, ?, ?, ?, ?, ?)
"""

data6 = map_user.values.tolist()

cursor.executemany(insert_query6, data6)
conn.commit()

print("Map User data inserted successfully!")

Map User data inserted successfully!

# top

In [34]:
insert_query7 = """
INSERT INTO top_insurance
(States, Years, Quarter, Pincodes, Transaction_count, Transaction_amount)
VALUES (?, ?, ?, ?, ?, ?)
"""

data7 = top_insur.values.tolist()

cursor.executemany(insert_query7, data7)
conn.commit()

print("Top Insurance data inserted successfully!")

Top Insurance data inserted successfully!

In [35]:
insert_query8 = """
INSERT INTO top_transaction
(States, Years, Quarter, Pincodes, Transaction_count, Transaction_amount)
VALUES (?, ?, ?, ?, ?, ?)
"""

data8 = top_transaction.values.tolist()

cursor.executemany(insert_query8, data8)
conn.commit()

print("Top Transaction data inserted successfully!")

Top Transaction data inserted successfully!

In [36]:
insert_query9 = """
INSERT INTO top_user
(States, Years, Quarter, Pincodes, RegisteredUser)
VALUES (?, ?, ?, ?, ?)
"""

data9 = top_user.values.tolist()

cursor.executemany(insert_query9, data9)
conn.commit()

print("Top User data inserted successfully!")

Top User data inserted successfully!